#!/bin/bash

# 编译选项
# 编译选项 - 使用环境变量覆盖默认值
BUILD_QTBASE_EXAMPLES=${BUILD_QTBASE_EXAMPLES:-OFF}
BUILD_QT3D_EXAMPLES=${BUILD_QT3D_EXAMPLES:-OFF}
BUILD_QTQUICK3D_EXAMPLES=${BUILD_QTQUICK3D_EXAMPLES:-OFF}

# 打印编译选项
echo "BUILD_QTBASE_EXAMPLES: $BUILD_QTBASE_EXAMPLES"
echo "BUILD_QT3D_EXAMPLES: $BUILD_QT3D_EXAMPLES"
echo "BUILD_QTQUICK3D_EXAMPLES: $BUILD_QTQUICK3D_EXAMPLES"

rm -rf build
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/6.9.1 \
    -DBUILD_QTBASE_EXAMPLES=$BUILD_QTBASE_EXAMPLES \
    -DBUILD_QT3D_EXAMPLES=$BUILD_QT3D_EXAMPLES \
    -DBUILD_QTQUICK3D_EXAMPLES=$BUILD_QTQUICK3D_EXAMPLES ..
make -j8
